apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vantage6-server
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: vantage6
        - name: POSTGRES_USER
          value: vantage6user
        - name: POSTGRES_PASSWORD
          value: vantage6password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"