version: '4'
services:

  vantage6-server:
    # build: .
    image: harbor2.vantage6.ai/infrastructure/server:latest
    dockerfile: server.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      # - ./configs/sqlite.yaml:/mnt/config.yaml
      - ./configs/postgress.yaml:/mnt/config.yaml
    command: [
      "uwsgi --http :5000 --gevent 1000 --http-websockets
        --master --callable app --disable-logging
        --wsgi-file /vantage6/vantage6-server/vantage6/server/wsgi.py
        --pyargv /mnt/config.yaml"
    ]

  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme