name: Build & Release

on:
  push:
    tags:
      - 'version/*.*.*'

jobs:

  # From the tag we split the individual version components:
  # major.minor.patch.stage<N>. Note that post releases are not part
  # of this schema as they are only used for releasing updated docker
  # images. This job also commits the version number to the git repo
  version:
    name: Apply version
    runs-on: ubuntu-latest
    steps:

      - name: split
        id: split
        run: |
          TAG=${GITHUB_REF#refs/*/}
          VERSION=${TAG#version/*}
          PARTS=(${VERSION//\./ })
          MAJOR=${PARTS[0]}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "major=${MAJOR}" >> $GITHUB_OUTPUT
          echo "minor=${PARTS[1]}" >> $GITHUB_OUTPUT
          PARTS2=( $(grep -Eo '[[:digit:]]+|[^[:digit:]]+' <<< ${PARTS[2]} ) )
          echo "patch=${PARTS2[0]}" >> $GITHUB_OUTPUT
          echo "stage=${PARTS2[1]}" >> $GITHUB_OUTPUT
          echo "build=${PARTS2[2]}" >> $GITHUB_OUTPUT
          MAJOR_NAME=''
          if [[ $MAJOR == '3' ]]; then MAJOR_NAME="petronas"; fi
          if [[ $MAJOR == '2' ]]; then MAJOR_NAME="harukas"; fi
          if [[ $MAJOR == '1' ]]; then MAJOR_NAME="trolltunga"; fi
          echo "major_name=${MAJOR_NAME}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.COMMIT_PAT }}

      - name: Update version in packages
        id: set_versions
        env:
          build: ${{ steps.split.outputs.build }}
          stage: ${{ steps.split.outputs.stage }}
          major: ${{ steps.split.outputs.major }}
          minor: ${{ steps.split.outputs.minor }}
          patch: ${{ steps.split.outputs.patch }}
        run: |
          BUILD="--build 0"; if [[ -n $build ]]; then BUILD="--build $build"; fi
          SPEC="--spec final"
          if [[ $stage == 'a' ]]; then SPEC="--spec alpha"; fi
          if [[ $stage == 'b' ]]; then SPEC="--spec beta"; fi
          if [[ $stage == 'rc' ]]; then SPEC="--spec candidate"; fi
          FLAGS="--version ${major}.${minor}.${patch} $BUILD --post 0 $SPEC"
          make set-version FLAGS="$FLAGS"

      - name: commit
        env:
          version: ${{ steps.split.outputs.version }}
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add *
          git checkout -b release/${version}
          git commit -m "Updated the version ${version}"
          git push --set-upstream origin release/${version}
          git checkout main
          git merge release/${version}
          git push

    outputs:
      version: ${{ steps.split.outputs.version }}
      major: ${{ steps.split.outputs.major }}
      minor: ${{ steps.split.outputs.minor }}
      patch: ${{ steps.split.outputs.patch }}
      stage: ${{ steps.split.outputs.stage }}
      build: ${{ steps.split.outputs.build }}
      major_name: ${{ steps.split.outputs.major_name }}

  # Create Github release which can be used DOI generation
  github-release:
    runs-on: ubuntu-latest
    needs: version
    env:
      version: ${{ needs.version.outputs.version }}
      stage: ${{ needs.version.outputs.stage }}
    steps:
    - uses: actions/checkout@v3
      with:
        # we just made a version commit, so we need to pull that. Else the
        # commit of the tag is used.
        ref: 'main'

    - name: Create a Release
      uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.version }}"
        prerelease: ${{ env.stage != '' }}
        title: "${{ env.version }}"

  support-images:
    name: Build support images
    runs-on: ubuntu-latest
    needs: version
    env:
      version: ${{ needs.version.outputs.version }}

    steps:

      - name: Login to harbor2.vantage6.ai
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: docker login harbor2.vantage6.ai -u $USERNAME -p $PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we just made a version commit, so we need to pull that. Else the
          # commit of the tag is used.
          ref: 'main'

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # We need this for building multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build support images
        run: make support-image TAG=$version

  infrastructure-images:
    name: Build infrastructure images
    runs-on: ubuntu-latest
    needs: version
    env:
      version: ${{ needs.version.outputs.version }}
      major: ${{ needs.version.outputs.major }}
      minor: ${{ needs.version.outputs.minor }}
      patch: ${{ needs.version.outputs.patch }}
      stage: ${{ needs.version.outputs.stage }}

    steps:

      - name: Login to harbor2.vantage6.ai
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: docker login harbor2.vantage6.ai -u $USERNAME -p $PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we just made a version commit, so we need to pull that. Else the
          # commit of the tag is used.
          ref: 'main'

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - # We need this for building multi-arch images
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - # vpn images
        name: Build Docker support images
        run: make support-image TAG=$version

      - # we only release a new base image if it is a major release
        name: Build Docker base image
        if: ${{ env.minor == 0 && env.patch == 0 && env.stage == '' }}
        run: make base-image TAG=$major

      - # build the actual infrastructure images
        name: Build Docker image
        run: make image TAG=$version BASE=$major

  algorithm-base-image:
    name: Build algorithm base image
    runs-on: ubuntu-latest
    needs: version
    env:
      version: ${{ needs.version.outputs.version }}

    steps:
      - name: Login to harbor2.vantage6.ai
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: docker login harbor2.vantage6.ai -u $USERNAME -p $PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we just made a version commit, so we need to pull that. Else the
          # commit of the tag is used.
          ref: 'main'


      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # We need this for building multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Algorithm base image
        run: make algorithm-base-image TAG=$version


  # Update the server and node images on harbor2 for this major version,
  # including the 'live' tag that triggers a redeployment of the IKNL deployment
  deploy:
    runs-on: ubuntu-latest
    needs: [version, infrastructure-images]
    env:
      version: ${{ needs.version.outputs.version }}
      stage: ${{ needs.version.outputs.stage }}
      major_name: ${{ needs.version.outputs.major_name }}
    steps:

      - name: Login to harbor2.vantage6.ai
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login harbor2.vantage6.ai -u $USERNAME -p $PASSWORD

      - name: Pull docker images
        if: ${{  env.stage == ''  &&  env.major_name != '' }}
        run: |
          docker pull harbor2.vantage6.ai/infrastructure/server:${version}
          docker pull harbor2.vantage6.ai/infrastructure/node:${version}

      - name: Tag docker images
        if: ${{  env.stage == ''  &&  env.major_name != '' }}
        run: |
          docker tag harbor2.vantage6.ai/infrastructure/server:${version} harbor2.vantage6.ai/infrastructure/server:${major_name}
          docker tag harbor2.vantage6.ai/infrastructure/server:${version} harbor2.vantage6.ai/infrastructure/server:${major_name}-live
          docker tag harbor2.vantage6.ai/infrastructure/node:${version} harbor2.vantage6.ai/infrastructure/node:${major_name}

      - name: Push docker images
        if: ${{  env.stage == ''  &&  env.major_name != '' }}
        run: |
          docker push harbor2.vantage6.ai/infrastructure/server:${major_name}
          docker push harbor2.vantage6.ai/infrastructure/server:${major_name}-live
          docker push harbor2.vantage6.ai/infrastructure/node:${major_name}

  # Build an release all the vantage6 infrastructure packages. For all
  # the packages it will (1) update the version as specified in the tag,
  # (2) build the package, (3) upload it to pypi, and (4) build and push
  # the Docker image
  build-n-release:

    name: Build and release the project
    runs-on: ubuntu-latest
    needs: version
    env:
      version: ${{ needs.version.outputs.version }}
      major: ${{ needs.version.outputs.major }}
      minor: ${{ needs.version.outputs.minor }}
      patch: ${{ needs.version.outputs.patch }}
      stage: ${{ needs.version.outputs.stage }}
      build: ${{ needs.version.outputs.build }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we just made a version commit, so we need to pull that. Else the
          # commit of the tag is used.
          ref: 'main'

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click
          pip install wheel
          pip install twine

      - name: Build project
        id: make
        run: |
          make rebuild

      - name: Publish project to PyPi
        id: publish
        if: ${{ !env.ACT }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          make publish

  # When the project is built and released the Discord community is notified.
  notify:
    runs-on: ubuntu-latest
    needs: [version, infrastructure-images]
    env:
      version: ${{ needs.version.outputs.version }}
      stage: ${{ needs.version.outputs.stage }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # we just made a version commit, so we need to pull that. Else the
          # commit of the tag is used.
          ref: 'main'

      - name: Install dependencies
        run: |
          pip install discord.py==1.7.3
          pip install click

      - name: Notify Discord community
        if: ${{  env.stage == '' }}
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_RELEASE_TOKEN }}
        run: |
          make community FLAGS="--version $version --notes '' \
            --post-notes ''"
